### ISSUE TITLE
Backflip trajectory

### ISSUE THREAD

**Issue by giulianodejulio** [maximekli/pie-solo-2122#1]
Hello,
I am trying to generate a backflip trajectory for Solo with Crocoddyl and I was wondering if somebody has already achieved such result. If you did, I would be very interested in the code.
Thanks in advance :-)

**Comment by maximekli** [comment]
Hi! Complete answer to come, following our discussion on Element.

**Comment by maximekli** [comment]
As discussed together:

> Using Crocoddyl, we managed to get a simple vertical jump, a "yaw jump" and a semi-backflip. The full backflip trajectory was obtained using simple physics, "by hand".
> 
> However, we tested only the first two on the robot itself, because we were not 100% confident that the backflips would translate in the real world without breaking anything, and we were lacking time before the end of the year. We believe they could be used to warm-start a new optimization though, hopefully yielding better results.
> 
> You can find everything by browsing the subdirectory of the OC directory: https://github.com/maximekli/pie-solo-2122/tree/main/OC.

I will then close this issue.
